language: python
matrix:
  include:
  - env: TARGET=pypi
sudo: required
services:
 - docker
install:
 - true
script:
 - docker build . -f .travis/${TARGET}.docker
deploy:
  provider: pypi
  user: gijzelaerr
  password:
    secure: xDkz2ilo/rG1U1dSfhAJoFXAVcmw+L0uk7DUuAtRhDh/ShpULlU9F3MPtVHo2fGmzgjVy1Joiya1iTveHdLvnwMpd10QZcygq712GjS6Z4Oum1poUwzFXfgyU97xYWoYsgfv/5n4Ae6zhMemHrp3qvDybFWJzmPPPh1GNba3pVQ=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: ska-sa/owlcat
