language: python
python:
- '2.7'
install:
- python setup.py install
script:
- true
deploy:
  provider: pypi
  user: gijzelaerr
  password:
    secure: xDkz2ilo/rG1U1dSfhAJoFXAVcmw+L0uk7DUuAtRhDh/ShpULlU9F3MPtVHo2fGmzgjVy1Joiya1iTveHdLvnwMpd10QZcygq712GjS6Z4Oum1poUwzFXfgyU97xYWoYsgfv/5n4Ae6zhMemHrp3qvDybFWJzmPPPh1GNba3pVQ=
  on:
    tags: true
